project:
  type: website

website:
  title: "Vivian"
  description: "This is Vivian's personal Blog."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Vivianapika/Vivianapika.github.io
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto

