project:
  type: website

website:
  title: "Vivian"
  description: "This is Vivian's personal Blog."
  navbar:
    right:
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto

