---
title: "Declutter"
author: "Vivian"
date: "2024-06-10"
categories: [story]
---

## Phone addiction
Do I want to start the day by playing video games and scrolling the short videos or watching long videos? No I don't. I need some intervention. What can I do to help myself from doing it over and over again? How exactly? It's not fair.
Maybe one thing I can do is to start the day with reviewing my todoist list. I don't want to see stuff that is overdue to be honest.

My solution is to switch to a phone with smaller screen. So far it's the best option, because I had to have a working gps navigation for my car drive. And after I read about all the options for dumbphones, this phone jump out to me. I ordered this one and next step is to get rid of my iphone and ipod, once and for all. Most tasks can be done on my mac, and it'll be how it works. Including the todo list app I've been working with.
Jelly Star - The World's Smallest Android 13 Smartphone
[https://www.unihertz.com/](https://www.unihertz.com/)

In order to get rid of iphone, what do I need to do?
[https://support.apple.com/en-us/109511](https://support.apple.com/en-us/109511)
[x] deregister iMessage
[x] unpair your Apple Watch
[ ] backup the phone
